# motion module v1_14
- dreambooth_path: "models/DreamBooth_LoRA/toonyou_beta6.safetensors"
  lora_model_path: ""

  inference_config: "configs/inference/inference-v1.yaml"
  motion_module:    "models/Motion_Module/mm_sd_v14.ckpt"

  seed: [10788741199826055526, 6520604954829636163, 6519455744612555650, 16372571278361863751]
  steps: 25
  guidance_scale: 8

  prompt:
    - "best quality, masterpiece, 1girl, looking at viewer, blurry background, upper body, contemporary, dress"
    - "masterpiece, best quality, 1girl, solo, cherry blossoms, hanami, pink flower, white flower, spring season, wisteria, petals, flower, plum blossoms, outdoors, falling petals, white hair, black eyes,"
    - "best quality, masterpiece, 1boy, formal, abstract, looking at viewer, masculine, marble pattern"
    - "best quality, masterpiece, 1girl, cloudy sky, dandelion, contrapposto, alternate hairstyle,"

  n_prompt:
    - "worst quality, low quality, letterboxed"


# motion module v1_15
- dreambooth_path: "models/DreamBooth_LoRA/toonyou_beta6.safetensors"
  lora_model_path: ""

  inference_config: "configs/inference/inference-v1.yaml"
  motion_module:    "models/Motion_Module/mm_sd_v15.ckpt"

  seed: [10788741199826055526, 6520604954829636163, 6519455744612555650, 16372571278361863751]
  steps: 25
  guidance_scale: 8

  prompt:
    - "best quality, masterpiece, 1girl, looking at viewer, blurry background, upper body, contemporary, dress"
    - "masterpiece, best quality, 1girl, solo, cherry blossoms, hanami, pink flower, white flower, spring season, wisteria, petals, flower, plum blossoms, outdoors, falling petals, white hair, black eyes,"
    - "best quality, masterpiece, 1boy, formal, abstract, looking at viewer, masculine, marble pattern"
    - "best quality, masterpiece, 1girl, cloudy sky, dandelion, contrapposto, alternate hairstyle,"

  n_prompt:
    - "worst quality, low quality, letterboxed"
